[project]
name = "osprey-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "osprey_rpc"
]
[project.entry-points."osprey_plugin"]
stdlib = "osprey.worker._stdlibplugin"
